trigger:
- dev

stages: 

- stage: applicationSecurity
  jobs:
    - template: ../../templates/application-security.yaml
      parameters:
        agent_pool: private-vm-pool-dev

- stage: unitTest
  jobs: 
    - template: ../../templates/test.yaml
      parameters:
        agent_pool: private-vm-pool-dev

- stage: buildScanAndPush
  jobs: 
    - template: ../../templates/build-scan-push-images.yaml
      parameters:
        azureSubscription: dev-oidc-connection
        agent_pool: private-vm-pool-dev

- stage: updateHelmManifests
  jobs: 
    - template: ../../templates/update-helm-manifests.yaml
      parameters:
        agent_pool: private-vm-pool-dev

- stage: provisionTerraformResources
  jobs: 
    - template: ../../templates/provision-resources.yaml
      parameters:
        azureSubscription: dev-oidc-connection
        agent_pool: private-vm-pool-dev

- stage: installHelmChartInCluster
  jobs: 
    - template: ../../templates/provision-resources.yaml
      parameters:
        azureSubscription: dev-oidc-connection
        cluster_name: silasdev-k8-cluster
        resource_group: dev
        agent_pool: private-vm-pool-dev
