trigger:
- dev

stages: 

- stage: applicationSecurity
  jobs:
    - template: pipelines/templates/application-security.yaml
      parameters:
        agent_pool: private-vm-pool-dev

- stage: unitTest
  jobs: 
    - template: pipelines/templates/test.yaml
      parameters:
        agent_pool: private-vm-pool-dev

- stage: buildScanAndPush
  jobs: 
    - template: pipelines/templates/build-scan-push-images.yaml
      parameters:
        azureSubscription: dev-oidc-connection
        agent_pool: private-vm-pool-dev

- stage: updateHelmManifests
  jobs: 
    - template: pipelines/templates/update-helm-manifests.yaml
      parameters:
        agent_pool: private-vm-pool-dev

- stage: provisionTerraformResources
  jobs: 
    - template: pipelines/templates/provision-resources.yaml
      parameters:
        azureSubscription: dev-oidc-connection
        agent_pool: private-vm-pool-dev

- stage: installHelmChartInCluster
  jobs: 
    - template: pipelines/templates/provision-resources.yaml
      parameters:
        azureSubscription: dev-oidc-connection
        cluster_name: 
        resource_group:
        agent_pool: private-vm-pool-dev
