env: main

apps:
  namespace: apps-namespace
  fastapi:
    replicas: 2
    image: silasmain.azurecr.io/backend/fastapi:c4505fc-0000-gc4505fc
    resources: 
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
  reactRecoil:
    replicas: 2
    image: silasmain.azurecr.io/frontend/react-recoil:c4505fc-0000-gc4505fc
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 1Gi
external_secrets:
  secret_store_name: azure-store
  vault_uri: https://silas-main-key-vault.vault.azure.net
  managed_identity_id: 
