trigger:
- main

stages: 

- stage: applicationSecurity
  jobs:
    - template: templates/application-security.yaml
      parameters:
        agent_pool: private-vm-pool-main

- stage: unitTest
  jobs: 
    - template: templates/test.yaml
      parameters:
        agent_pool: private-vm-pool-main

- stage: buildScanAndPush
  jobs: 
    - template: templates/build-scan-push-images.yaml
      parameters:
        azureSubscription: main-oidc-connection
        agent_pool: private-vm-pool-main

- stage: updateHelmManifests
  jobs: 
    - template: /templates/update-helm-manifests.yaml
      parameters:
        agent_pool: private-vm-pool-main

- stage: provisionTerraformResources
  jobs: 
    - template: templates/provision-resources.yaml
      parameters:
        azureSubscription: main-oidc-connection
        agent_pool: private-vm-pool-main

- stage: installHelmChartInCluster
  jobs: 
    - template: templates/provision-resources.yaml
      parameters:
        azureSubscription: main-oidc-connection
        cluster_name: 
        resource_group:
        agent_pool: private-vm-pool-main
