apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.apps.namespace }}
  annotations:
    alb.networking.azure.io/alb-namespace: azure-alb-system
    alb.networking.azure.io/alb-name: azure-alb
spec:
  gatewayClassName: {{ .Values.gateway_class.name }}
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: my-app-tls-secret
          namespace: {{ .Values.apps.namespace }}
    - name: http
      port: 80
      protocol: HTTP
