jobs:
- template: ./filter-directories.yaml
  parameters:
    services: |
      backend/fastapi
      frontend/react-recoil

- job: semgrepScan
  dependsOn: filterDirectories
  variables:
    CHANGED_DIR: $[dependencies.filterDirectories.outputs['getUpdatedDirectories.dir_changed']]
  strategy:
    matrix:
      backend:
        dir: backend/fastapi
      frontend:
        dir: frontend/react-recoil
  pool:
    vmImage: ubuntu-24.04
  container: semgrep/semgrep
  
  steps:
  - checkout: self
    displayName: Checkout Code

  - template: ./templated-steps/get-updated-dir.yaml
    parameters:
      changedDir: $(CHANGED_DIR)

  - script: |
      semgrep scan --config auto $(updated_dir)
    displayName: Semgrep Scan
    condition: and(succeeded(), ne(variables['updated_dir'], ''))
    env:
      SEMGREP_APP_TOKEN: $(SEMGREP_APP_TOKEN)

      #  always lead with the step type (checkout, script, task, template) and put everything else after