parameters:
  - name: services
    type: string
    default: ''
  - name: agent_pool
    type: string

jobs:
- job: filterDirectories
  displayName: Filter only updated directories
  pool: 
    name: ${{ parameters.agent_pool }}
  variables:
    services: ${{ parameters.services }}
  steps:
  - checkout: self
    displayName: Checkout Code

  - script: |
      echo "Detecting changed directories"
      CHANGED_SERVICES=""
      for svc in $(services); do
        if git diff --name-only HEAD~1 HEAD | grep -q "^$svc/"; then
          echo "$svc changed"
          CHANGED_SERVICES="$CHANGED_SERVICES $svc"
        fi
      done
      echo "##vso[task.setvariable variable=dir_changed;isOutput=true]$CHANGED_SERVICES"
    displayName: Get Updated Directories
    name: getUpdatedDirectories
