parameters:
  - name: azureSubscription
    type: string
  - name: cluster_name
    type: string
  - name: resource_group
    type: string
  - name: agent_pool
    type: string

jobs:
- job: installHelmChart
  displayName: Install Helm Chart
  pool:
    name: ${{ parameters.agent_pool }}
  steps:
  - checkout: self
    displayName: Checkout Code

  - task: AzureCLI@2
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az account show

        az aks get-credentials --name ${{ parameters.cluster_name }} --resource-group ${{ parameters.resource_group }} --overwrite-existing

        # install app helm chart
        helm upgrade --install app helm/app \
        -f helm/app/env/$(Build.SourceBranchName)/values.yaml \
        -n apps-namespace \
        --create-namespace \
        --wait --timeout 5m

        # install chart for platform configs (GatewayClass, Gateway API, HTTP Route)
        helm upgrade --install platform helm/platform \
        -f helm/platform/env/$(Build.SourceBranchName)/values.yaml \
        -n apps-namespace \
        --create-namespace \
        --wait --timeout 5m

        #apply cert manager certificates
        kubectl apply -f helm/002_certificate_issuer.yaml
        kubectl apply -f helm/003_certificate.yaml