parameters:
  - name: agent_pool
    type: string

jobs:
- template: ./filter-directories.yaml
  parameters:
    services:
      - backend/fastapi
      - frontend/react-recoil
    agent_pool: ${{ parameters.agent_pool }}

- job: test
  dependsOn: filterDirectories
  displayName: Run unit tests
  variables:
    CHANGED_DIR: $[dependencies.filterDirectories.outputs['getUpdatedDirectories.dir_changed']]
  strategy:
    matrix:
      backend:
        dir: backend/fastapi
      frontend:
        dir: frontend/react-recoil
  pool:
    name: ${{ parameters.agent_pool }}
  condition: ne(variables['CHANGED_DIR'], '')
  
  steps:
  - checkout: self
    displayName: Checkout code
  
  - template: ../templated-steps/get-updated-dir.yaml
    parameters:
      changedDir: $(CHANGED_DIR)
  
  - script: |
      python --version
      pip --version
    condition: contains(variables['updated_dir'], 'backend/fastapi')
    displayName: Verify Python

  - task: Cache@2
    inputs:
      key: 'python | "$(Agent.OS)" | $(Build.SourcesDirectory)/$(updated_dir)/requirements.txt'
      path: $(Pipeline.Workspace)/.pip
      restoreKeys: |
        python | "$(Agent.OS)"
    condition: contains(variables['updated_dir'], 'backend/fastapi')
    displayName: Cache pip packages

  - task: NodeTool@0
    inputs:
      versionSpec: '24.x' 
    condition: contains(variables['updated_dir'], 'frontend/react-recoil')
    displayName: Set up Node environment
  
  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | $(Build.SourcesDirectory)/$(updated_dir)/yarn.lock'
      path:  $(Build.SourcesDirectory)/$(updated_dir)/node_modules
    condition: contains(variables['updated_dir'], 'frontend/react-recoil')
    displayName: Cache node_modules
  
  - script: |
     curl -sLf 'https://github.com/go-task/task/releases/download/v3.46.4/task_linux_amd64.tar.gz' \
      | sudo tar -xz -C /usr/local/bin task
     task --version
    condition: ne(variables['updated_dir'], '')
    displayName: Install Task CLI
  
  - script: |
      cd $(updated_dir)
      task install_dependencies_ci
    condition: ne(variables['updated_dir'], '')
    displayName: Install Dependencies

  - script: |
      cd $(updated_dir)
      task test
    condition: ne(variables['updated_dir'], '')
    displayName: Run tests