parameters:
  - name: agent_pool
    type: string
    
jobs:
- template: ./filter-directories.yaml
  parameters:
    services:
      - backend/fastapi
      - frontend/react-recoil
    agent_pool: ${{ parameters.agent_pool }}

- job: updateHelmManifests
  dependsOn: filterDirectories
  displayName: Update Helm Values
  variables:
    CHANGED_DIR: $[dependencies.filterDirectories.outputs['getUpdatedDirectories.dir_changed']]
  strategy:
    matrix:
      backend:
        dir: backend/fastapi
      frontend:
        dir: frontend/react-recoil
  pool:
    name: ${{ parameters.agent_pool }}
  steps:
  - checkout: self
    displayName: Checkout Code
    persistCredentials: true

  - template: ../templated-steps/get-updated-dir.yaml
    parameters:
      changedDir: $(CHANGED_DIR)

  - script: |
      jq --version
      yq --version
    displayName: Verify jq and yq versions in vm 

  - script: |
        BRANCH=$(Build.SourceBranchName)
        TARGET_DIR="helm/app/env/$BRANCH"
        HELM_VALUES_FILE="$TARGET_DIR/values.yaml"

        if [ "$(updated_dir)" == "backend/fastapi" ]; then
         TARGET_FILE="$TARGET_DIR/fastapi.json"
        elif [ "$(updated_dir)" == "frontend/react-recoil" ]; then
         TARGET_FILE="$TARGET_DIR/react-recoil.json"
        else
         echo "$(updated_dir) is not a supported path"
         exit 1
        fi

        SERVICE=$(jq -r '.service' "$TARGET_FILE")
        IMAGE=$(jq -r '.image' "$TARGET_FILE")

        echo "Editing: $TARGET_FILE"
        echo "Service: $SERVICE"
        echo "Image: $IMAGE"

        echo "Updating $SERVICE image tag -> $IMAGE"

        if [ "$(updated_dir)" == "backend/fastapi" ]; then
          CURRENT=$(yq '.apps.fastapi.image' "$HELM_VALUES_FILE")
          echo "Current fastapi image: $CURRENT"
          echo "Editing image value"
          yq -i '.apps.fastapi.image = "'"$IMAGE"'"' "$HELM_VALUES_FILE"
        elif [ "$(updated_dir)" == "frontend/react-recoil" ]; then
          CURRENT=$(yq '.apps.reactRecoil.image' "$HELM_VALUES_FILE")
          echo "Current react-recoil image: $CURRENT"
          echo "Editing image value"
          yq -i '.apps.reactRecoil.image = "'"$IMAGE"'"' "$HELM_VALUES_FILE"
        else
         echo "$(updated_dir) is not a supported path"
         exit 1
        fi

        echo "Contents after update:"
        cat "$HELM_VALUES_FILE"

        echo "Git diff:"
        git diff "$HELM_VALUES_FILE"

        echo "##vso[task.setvariable variable=helm_values_file]$HELM_VALUES_FILE"
    condition: ne(variables['updated_dir'], '')
    displayName: Update helm values for all services

  - script: |
        HELM_VALUES_FILE =$(helm_values_file)

        git config user.name "Azure Pipeline"
        git config user.email "pipeline@example.com"

        if git diff --quiet "$HELM_VALUES_FILE"; then
            echo "No changes to commit"
        else
            git add "$HELM_VALUES_FILE"
            git commit -m "ci: update helm values for $UPDATED_DIR $BRANCH_NAME" || echo "No changes to commit"
            git pull --rebase origin $BRANCH_NAME
            git push origin HEAD:"$BRANCH_NAME"
        fi
    condition: ne(variables['updated_dir'], '')
    displayName: Commit and push Helm updates
    env:
      GITHUB_PAT: $(GITHUB_PAT)
      UPDATED_DIR: $(updated_dir)
      IS_MAIN: $(isMain)
      BRANCH_NAME: $(Build.SourceBranchName)