version: "3"

tasks:
  dev_runners:
    cmd: |
      # ansible dev_runners -i inventory.yaml -m ping
      ansible-playbook -i inventory.yaml vm-runner-config.yaml --limit dev_runners
    
  main_runners:
    cmd: |
      # ansible main_runners -i inventory.yaml -m ping
      ansible-playbook -i inventory.yaml vm-runner-config.yaml --limit main_runners

  private_runners:
    cmd: ansible-playbook -i inventory.yaml vm-runner-config.yaml --limit private_runners