version: "3"

env:
  AZURE_REGION: eastus2
  NAMESPACE: azure-alb-system
  RESOURCE_GROUP: dev
  CLUSTER_NAME: silasdev-k8-cluster
  VAULT_MANAGED_IDENTITY_NAME: silasdev-aks-identity


tasks:
    
  azure:connect-to-cluster:
    cmd:
        |
        az aks get-credentials \
        --resource-group ${RESOURCE_GROUP} \
        --name ${CLUSTER_NAME}
  
#Install External Secrets into cluster
  azure:install_external_secrets_for_vault:
    cmd:
      |
      helm repo add external-secrets https://charts.external-secrets.io

      helm install external-secrets \
        external-secrets/external-secrets \
          -n external-secrets \
          --create-namespace 
          #--set installCRDs=false

# install gateway api controllers
  azure:install_alb-controller:
      desc: Install azure alb controller with Gateway API support
      cmds:
        - kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/latest/download/standard-install.yaml
        - |
          MANAGED_IDENTITY_CLIENT_ID = (az identity show   --name ${MANAGED_IDENTITY_NAME}  --resource-group ${RESOURCE_GROUP} --query clientId -o tsv)
          helm install alb-controller oci://mcr.microsoft.com/application-lb/charts/alb-controller \
          --namespace ${NAMESPACE} \
          --create-namespace \
          --version 1.9.13 \
          --set albController.namespace=${NAMESPACE} \
          --set albController.podIdentity.clientID=$MANAGED_IDENTITY_CLIENT_ID
    
  cert_manager:install:
    desc: Install Cert Manager for TLS certificate configuration
    cmd: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.19.2/cert-manager.yaml


# k8 configs
  1:apply_namespace:
    cmd: kubectl apply -f 001_app_namespace.yaml

  2:apply_helm_config_for_app:
    cmd:
        |
         helm upgrade --install app app \
          -f app/env/dev/values.yaml \
          -n apps-namespace \
          --create-namespace \
          --wait --timeout 5m

  3:apply_platform_configs_for_app:
    cmd:
        |
          helm upgrade --install platform platform \
          -f platform/env/dev/values.yaml \
          -n apps-namespace \
          --create-namespace \
          --wait --timeout 5m

  4:get_k8_kv_identity:
    cmd: echo $(az identity show --name ${VAULT_MANAGED_IDENTITY_NAME}  --resource-group ${RESOURCE_GROUP} --query clientId -o tsv)

  5:apply_certificate_issuer:
    cmd: kubectl apply -f 002_certificate_issuer.yaml

  6:apply_certificate:
    cmd: kubectl apply -f 003_certificate.yaml