env: dev
apps:
  namespace: apps-namespace
  fastapi:
    replicas: 1
    image: silasdev.azurecr.io/backend/fastapi:c4505fc-0000-gc4505fc
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  reactRecoil:
    replicas: 1
    image: silasfrancis/devops-client-dev:e46aca1
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 1Gi
external_secrets:
  secret_store_name: azure-store
  vault_uri: https://silas-dev-key-vault.vault.azure.net
  managed_identity_id: e47f0b7f-cbe2-46d4-a9fd-cd4dd77c1446
