apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.external_secrets.secret_store_name }}
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      identityId: "{{ .Values.external_secrets.managed_identity_id }}"
      vaultUrl: "{{ .Values.external_secrets.vault_uri }}"
