apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fastapi-external-secrets
  namespace: {{ .Values.apps.namespace }}
spec: 
  refreshInterval: "1m"
  secretStoreRef:
    name: {{ .Values.external_secrets.secret_store_name }}
    kind: SecretStore
  target:
    name: fastapi-secrets # name of the k8 secret to be created
    creationPolicy: Owner
    data:
    - secretKey: SECRET_KEY  # key inside k8 secret
      remoteRef:
        key: SECRETKEY # Key Vault secret name

    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: JWTSECRETKEY

    - secretKey: POSTGRES_HOST
      remoteRef:
        key: POSTGRESHOST

    - secretKey: POSTGRES_PORT
      remoteRef:
        key: POSTGRESPORT

    - secretKey: POSTGRES_DB
      remoteRef:
        key: POSTGRESDB

    - secretKey: POSTGRES_USER
      remoteRef:
        key: POSTGRESUSER

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: POSTGRESPASSWORD